server:
  port: 0

app:
  dry-run: false

spring:
  datasource:
    url: jdbc:postgresql://chatalytics-stack:5432/postgres
    username: postgres
    password: postgrespassword

logging:
  level:
    org.jooq.tools.LoggerListener: ERROR
