name: dependabot-integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    if: github.actor == 'dependabot[bot]'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/wrapper-validation@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: ./gradlew build