server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://chatalytics-stack:5432/postgres
    username: postgres
    password: postgrespassword
  kafka:
    bootstrap-servers: chatalytics-stack:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

twitch:
  client-id: j9i0u85lh015x1b77yofg57lxx2mph
  client-secret: 4eodxhvvcqldlopw0ld02gmwc9w9ix
